# Generated by Django 5.2 on 2025-05-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0005_consultation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
