# Generated by Django 5.2 on 2025-05-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_consultationsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSales',
        ),
    ]
